### ISSUE TITLE
Submit to https://pub.dev/

### ISSUE THREAD

**Issue by bradintheusa** [iamvivekkaushik/DatePickerTimelineFlutter#1]
Hi

Are you planning on adding this to https://pub.dev/.  If so I'll wait otherwise I'll grab it now.

Brad (scrbrd.com)

**Comment by iamvivekkaushik** [comment]
Hi, it is already published on pub.dev here is the link https://pub.dev/packages/date_picker_timeline. I will add the same to readme.
