### ISSUE TITLE
Select dates from the past

### ISSUE THREAD

**Issue by mrwwalmsley** [iamvivekkaushik/DatePickerTimelineFlutter#10]
**Is your feature request related to a problem? Please describe.**
I am wanting to use this fantastic widget to select dates from the past. At present it seems to only work for future dates.

**Describe the solution you'd like**
Perhaps you could add a stateDate parameter that is set to today by default.

**Describe alternatives you've considered**
Fork the code and add the feature.

**Additional context**

**Comment by iamvivekkaushik** [comment]
Hi @mrwwalmsley, if you want the date to start at some previous time, then you can just pass that date to the constructor. 

```
DatePickerTimeline(
  DateTime.now(),
  onDateChange: (date) {
    // New date selected
    print(date.day.toString());
  },
),
```

Instead of date.now() you can pass any date and the calendar will start from that particular date.

**Comment by iamvivekkaushik** [comment]
Hi @mrwwalmsley, can you confirm if this resolves your issue?

**Comment by iamvivekkaushik** [comment]
I am closing this issue.

**Comment by mrwwalmsley** [comment]
Sorry for the late reply, I'm just getting on to implementing this functionality, and it doesn't seem to be working as I would like.

I want to set the current date to today... but allow the user to scroll back to select a day in the past.

**Comment by hinterlandsupplyco** [comment]
Any update on this? Can this PR #12 get merged in please?

**Comment by iamvivekkaushik** [comment]
I had no time to implement this, #12 have it implemented, you can use that version until it gets merged.

```
dependencies:
  date_picker_timeline:
    git:
      url: https://github.com/psygo/DatePickerTimelineFlutter.git
```

**Comment by HannHank** [comment]
I tried to pass the date like this `DateTime.now().add(Duration(days: -10)` to get the last week, but still see future dates.

**Comment by Mallington** [comment]
@HannHank Did you find a fix for this?

**Comment by HannHank** [comment]
@Mallington nope, still facing that problem.

**Comment by Mallington** [comment]
@HannHank I have posted a fix here: https://github.com/Mallington/DatePickerTimelineFlutter. You can modify your pubspec.yaml to use:
```
date_picker_timeline:
      git:
        url: https://github.com/Mallington/DatePickerTimelineFlutter
```
I'd recommend forking the repository for long term use, just in case I delete it 😄

**Comment by HannHank** [comment]
@Mallington  thanks 👍

**Comment by Mallington** [comment]
@HannHank There was an issue with my original commit. I have moved to setting the startDate in the constructor
See Example:
```
DatePickerTimeline(
   DateTime.now().add(Duration(days: -10)),
         onDateChange: (date) {
           // New date selected
           print(date.day.toString());
         },
         startDate: DateTime.now().add(Duration(days: -10)),
         daysCount: 10,
       )
```

**Comment by iamvivekkaushik** [comment]
Hi everyone, this option is now added to the library, just specify the `startDate` and the calendar will start from that particular date. I have also added a controller to move to any specific date.
