### ISSUE TITLE
Add button to slide back to Today's date

### ISSUE THREAD

**Issue by coolbeatz71** [iamvivekkaushik/DatePickerTimelineFlutter#22]
### Is your feature request related to a problem? Please describe.
I want to ask if the package has the feature where we can have a button to `automatically` slide back straight to today's date after sliding to some date far away from today's one.
 
### Describe the solution you'd like
If the feature does not exist, please I am requesting to add it.

### Describe alternatives you've considered
If the proposed feature is not worth to be implemented, I would like to get some tips on how I can do it myself with my custom methods without altering the package.

### Additional context
N/A

**Comment by iamvivekkaushik** [comment]
Hi @coolbeatz71, this package currently doesn't have such a feature. I will add the option to achieve this.

**Comment by coolbeatz71** [comment]
> Hi @coolbeatz71, this package currently doesn't have such a feature. I will add the option to achieve this.
Thank you @iamvivekkaushik , It's gonna be better to maybe expose a `public` method that can achieve this.

**Comment by iamvivekkaushik** [comment]
Hey, I have added a `DatePickerController`, you can use it to move the timeline to any date.
