### ISSUE TITLE
selection color is not changing on date selection

### ISSUE THREAD

**Issue by the-deadshot** [iamvivekkaushik/DatePickerTimelineFlutter#24]
when i am using setState() date is changing but selection color is not changing. if i am doing something wrong please let me know. 

 child: DatePickerTimeline(
                      DateTime.now(),
                      onDateChange: (date) {
                      
                        setState(() {
                          _date = date;
                        });
                      },

**Comment by iamvivekkaushik** [comment]
change `DateTime.now()` with the `date` variable.

```dart
DatePickerTimeline(
    date,
    onDateChange: (date) {
         setState(() {
             _date = date;
         });
  },
),
```

**Comment by the-deadshot** [comment]
@iamvivekkaushik thank you very much its working and thanks for your quick reply.
