### ISSUE TITLE
JumpToSelection() offset has issues.

### ISSUE THREAD

**Issue by amith-patil** [iamvivekkaushik/DatePickerTimelineFlutter#29]
**Describe the bug**

the JumpToSelection() function takes the time into consideration causing offset values to change during different times. 

**To Reproduce**

Create a startDate to be of the format "YYYY-MM-DD 00:00:00"
select initialSelectedDate as DateTime.now()
over the course of the day, on calling the JumpToSelection() for the first time via a separate button, the timeline will jump from to the date +1 value ( ex: if today is may 11th, JumpToSelection() will jump to May 12th after a period of the day has passed) 

**Expected behavior**

on initial jump, the timeline should jump to the initialSelectedDate Value

**Screenshots**

![ezgif-3-d1001ca39879](https://user-images.githubusercontent.com/51911194/81603645-507aa000-93ec-11ea-9d8f-496d3e0be24f.gif)

also, this weird thing happens, I'm not sure why : 

![ezgif-3-3c6cb3f8f3af](https://user-images.githubusercontent.com/51911194/81603664-5c666200-93ec-11ea-9c83-def942ca8027.gif)

**Additional context**

code used by me : 

```DateTime _startDate = DateTime.parse('2020-05-01 00:00:00Z');
  DateTime _selectedDate = DateTime.now();
.
.
.
DatePickerController _dpc = new DatePickerController();
.
.
.
DatePicker(
                          _startDate,
                          controller: _dpc,
                          initialSelectedDate: _selectedDate,
                          width: Size_Config.blockSizeHorizontal * 15,
                          height: Size_Config.blockSizeVertical * 12,
                          monthTextStyle: TextStyle(
                              fontFamily: 'Montserrat',
                              color: Colors.white54,
                              fontSize: Size_Config.blockSizeHorizontal * 3),
                          dateTextStyle: TextStyle(
                              fontFamily: 'MontSerrat',
                              fontSize: Size_Config.blockSizeHorizontal * 5,
                              fontWeight: FontWeight.bold,
                              color: Colors.white54),
                          dayTextStyle: TextStyle(
                              fontFamily: 'Montserrat',
                              color: Colors.white54,
                              fontSize: Size_Config.blockSizeHorizontal * 3),
                          onDateChange: (date) {
                            _pc.open();
                            setState(() {
                              _selectedDate = date;
                            });
                          },
                        ),
.
.
.
IconButton(
                                  onPressed: () {
                                    _dpc.animateToSelection();
                                  },
                                  icon: Icon(CustomIcons.filter),
                                  color: Colors.white54,
                                  //iconSize: 40,
                                ),

**Comment by iamvivekkaushik** [comment]
Hi Amith, can you remove the width argument from the DatePicker widget and check if you still have this issue.

**Comment by amith-patil** [comment]
> Hi Amith, can you remove the width argument from the DatePicker widget and check if you still have this issue.

I removed the width for the datepicker widget and I still see the problem,

So yesterday night around 1 am when I was working on it, it showed the correct date jump, now it's showing the 13th instead of the 12th. you can repro this by changing the date of the phone .

**Comment by amith-patil** [comment]
I think it's got something to do with the timestamp on the _currentDate item.

**Comment by iamvivekkaushik** [comment]
Okay, thanks for the insight.

**Comment by iamvivekkaushik** [comment]
Hi @amith-patil, I've fixed the issue you were facing and released a new version. I am closing this issue.
