### ISSUE TITLE
Provide a `lastDate` option

### ISSUE THREAD

**Issue by Akora-IngDKB** [iamvivekkaushik/DatePickerTimelineFlutter#35]
It will be nice to be able to provide a last date. It will be an efficient option to prevent performance issue on low end devices due to the infinite scrolling.

**Comment by iamvivekkaushik** [comment]
Hi, there is a last date option already available. You can pass the number of days that you wanna show after the start date `daysCount` in the constructor.

**Comment by Akora-IngDKB** [comment]
Oh how did I miss that 😆 .
