### ISSUE TITLE
Text color not changing on dark mode

### ISSUE THREAD

**Issue by nidhinmahesh** [iamvivekkaushik/DatePickerTimelineFlutter#38]
**Describe the bug**
Dark mode do not change the black text color of dates. Also there is no option to change color of dates which are not selected.

**Comment by iamvivekkaushik** [comment]
Hi @nidhinmahesh, This currently does not support the dark mode. However, you can override the text color for both selected or non selected items. Check the constructor and pass these parameters values

```dart
DatePicker(
    this.startDate,
    this.monthTextStyle = TextStyle(),
    this.dayTextStyle = TextStyle(),
    this.dateTextStyle = TextStyle()
} 
```
