### ISSUE TITLE
Jump to specific date?

### ISSUE THREAD

**Issue by chschroe** [iamvivekkaushik/DatePickerTimelineFlutter#40]
Hey guys,

first we really enjoy your work and love the datepicker timeline.

We are searching for a feature to jump to a specific date.
Example: timeline is on 01.01.2020, users press a button with "12.12.2020" and the timeline jumps to this date immediately.

Do you have any idea or implementation for this?
Would be very helpful for lots of users we think.

Thanks for your attention.

**Comment by william-levi** [comment]
Hi @iamvivekkaushik  need help here.. the animateToDate is working but the date is not highlighted.

https://user-images.githubusercontent.com/25534399/118352982-f2e8d880-b596-11eb-8806-7328ed35a777.mp4


also how to change the offset so that the selected date will be always on the center

**Comment by iamvivekkaushik** [comment]
> Hi @iamvivekkaushik  need help here.. the animateToDate is working but the date is not highlighted.
> 
> https://user-images.githubusercontent.com/25534399/118352982-f2e8d880-b596-11eb-8806-7328ed35a777.mp4
> 
> 
> also how to change the offset so that the selected date will be always on the center

AnimateToDate only animates scrolls to a date that you passed. Also there is currently no way for the selected date to be always in center.

**Comment by william-levi** [comment]
@iamvivekkaushik  thanks , no worries with the centering.
But how to make the selected date highlighted or isSelected ? when clicking on a specific button.

**Comment by developerflutter** [comment]
"DatePickerController is not attached to any DatePicker View" - when calling this animateTo function in initstate!
