### ISSUE TITLE
What's the use of setDatePickerState ? and how to use it

### ISSUE THREAD

**Issue by william-levi** [iamvivekkaushik/DatePickerTimelineFlutter#53]
Actually I'm trying to set the date programatically by clicking from a button

**Comment by iamvivekkaushik** [comment]
I've added a new function to the controller `setDateAndAnimate` you will need to use the github version of this repo in your project.

**Comment by william-levi** [comment]
@iamvivekkaushik  thanks ! nice package by the way :)

**Comment by iamvivekkaushik** [comment]
Thank you!

**Comment by ChineOnw** [comment]
Unfortunately the UI does not change. When I debugged it the variable has the new value, but the UI is not changing.

**Comment by ChineOnw** [comment]
> Unfortunately the UI does not change. When I debugged it the variable has the new value, but the UI is not changing.

I just wrapped the method call inside `setState()` and it works fine.
