### ISSUE TITLE
Select Date Perimeters.

### ISSUE THREAD

**Issue by vegeta-ssaiyan** [iamvivekkaushik/DatePickerTimelineFlutter#6]
**Is your feature request related to a problem? Please describe.**
Thanks for creating this Vivek. An issue I have is that the dates are continuous. It will be great if we are able to specify the dates we want the date picker to run for.

**Describe the solution you'd like**
A function that allows to specify the number of days, weeks, months from DateTime.now().
Or the function the allows us to add or subtract days from DateTime.now()

**Describe alternatives you've considered**
Using a different picker. or creating a selector on my own. Which is not efficient, as we already have such a sick date picker here, we just need to have more options.

**Additional context**
A little tweaks here and there and it'll be amazing. Thanks for creating this once again.

**Comment by iamvivekkaushik** [comment]
Hi @vegeta-ssaiyan, Thanks for using the package and taking the time to give your feedback. I will love to add this feature to the library soon.

**Comment by vegeta-ssaiyan** [comment]
Thanks Vivek! Have a nice one!

**Comment by iamvivekkaushik** [comment]
Hi @vegeta-ssaiyan, I have made some changes to the library. Now you can specify for how many days you want the list to go on. You can specify `daysCount` in the constructor. Hope this solves your problem. 🙃
