### ISSUE TITLE
change format locale

### ISSUE THREAD

**Issue by Jean-Alves** [iamvivekkaushik/DatePickerTimelineFlutter#8]
how do i change the format language, for example, i'm from brazil, how do i show up the week in brazilian format

**Comment by rogermedeirosdasilva** [comment]
Hi man, I added the locale parameter for the correct translation. I believe it is not published in the pub yet.

**Comment by iamvivekkaushik** [comment]
Hi @Jean-Alves, I have published a new version with the option to specify a locale. And thanks @rogermedeirosdasilva for your contribution.
