### ISSUE TITLE
This Date Picker dependancy not working on latest flutter version

### ISSUE THREAD

**Issue by jaydipdioneapps** [iamvivekkaushik/DatePickerTimelineFlutter#82]
The current Dart SDK version is 3.0.2.

Because date_picker_timeline >=1.2.3 depends on intl ^0.17.0 and date_picker_timeline <1.2.3 doesn't support null safety, every version of date_picker_timeline requires intl ^0.17.0.
So, because prarthi depends on both intl ^0.18.1 and date_picker_timeline any, version solving failed.

The lower bound of "sdk: '>=2.1.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
exit code 1

**Comment by iamvivekkaushik** [comment]
Resolved
