### ISSUE TITLE
Locale data has not been initialized

### ISSUE THREAD

**Issue by istepler** [iamvivekkaushik/DatePickerTimelineFlutter#9]
Hi, thanks for very good library. But I have the issue. I am new in Flutter, so maybe doing smth wrong. 

Implemented the last library version with locale, but get an error

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following LocaleDataException was thrown building DateWidget(dirty):
Locale data has not been initialized, call initializeDateFormatting(<locale>).

https://pasteboard.co/IzOhjdB.png

**Comment by iamvivekkaushik** [comment]
Hi @istepler, thanks for letting me know about the issue. You aren't doing anything wrong, I forgot to initialize the DateFormatting in the previous version. I have fixed the issue and will publish it now.

**Comment by istepler** [comment]
Thanks! Very quick work
